### PR TITLE
adds in functionality for using Google Forms as a request platform

### LINKED ISSUE #284: Display a button in the sidebar to request a component with containers
Subtask of #243. 

**Acceptance criteria**

* A button that reads "Request container(s)" should appear in the "in-person" section of the sidebar

**Mockup**

screen shot 2017-04-30 at 11 15 58 pm

### PR DESCRIPTION
**Pull request by mejackreed**
Closes #284 

I would also argue for closing #294. I think those specifications there may be in flux as someone implementing requests modify things.

request

### CODE REVIEW

**Comment by jkeck** [comment]
Looks good @mejackreed.  Quick question: Are we doing anything w/ the collection creator or the hierarchy in this PR or is that going to be pulled out in another ticket?  I feel like I saw some convo fly around about this but can't find it now.

**Comment by mejackreed** [comment]
@jkeck At the moment, no. 

cc @anarchivist I have some thoughts on all of that. Is it really data that needs to be part of this ticket to complete? I'm wondering if including the requested item url is sufficient instead to provide the appropriate context.

**Comment by anarchivist** [comment]
@mejackreed @jkeck I've broken out the collection creator indexing into #310. I don't think it's necessary to deliver this ticket. I like Jack's idea of adding a link to the component.

**Comment by jkeck** [comment]
Should this PR include the item URL in the form?  It's unclear to me if that's happening currently, apologies if it is and I'm just not seeing it.

**Comment by mejackreed** [comment]
@jkeck I've gone ahead and added the url to the form.

**Pull request merged**
