### PR TITLE
Navigating through the murky hierarchy

### LINKED ISSUE #149: Collection detail page - contents/inventory section MVP
The MVP for the contents section of the collections detail page displays information about the immediate children of the top-level description. 

**Acceptance criteria**

* A navigation bar that allows a user to switch between the summary section and the contents section
* If there are children of the top-level description:
    * There should be an entry for each child of the top-level description, which displays the following information:
        * Title and/or dates as one string, and component identifier (`<unitid/>`) if available, linking to the appropriate component-level show page
        * The first ~175 characters of the scope and content note (if available)
    * The entry in the nav bar should read "Contents"
    * The children should be displayed in order as they appear in the source data -- **CAN BE BROKEN INTO A NEW TICKET**
* If there are no children of the top-level description:
    * The entry in the nav bar should read "No content inventory" and not be clickable

**Out of Scope for this ticket**

* A label indicating the number of children of that child, with the appropriate level if identifiable (#189)

**Mockups**

collection-detail-contents

arclight-mockups-mvp

### PR DESCRIPTION
**Pull request by mejackreed**
Closes #149 

This PR also adds in JavaScript linting / stylechecking to our build

hierarchy

### CODE REVIEW

**Comment by jkeck** [comment]
@mejackreed I think there may be a bug w/ how the result view and the session history is working.  After viewing the content inventory it appears that view type is pinned to my session, and future search results default to being rendered using that view-type.

results-view-type-bug

**Comment by mejackreed** [comment]
@jkeck checkout 4c8f956570cc1d8995642e35cc19429a61e16371 and see if that works for you

**Comment by jkeck** [comment]
Taking it for a 🚗 now. 🕶

**Comment by jkeck** [comment]
Hmm, so I am still experiencing the same behavior.  I'm not sure the test, as written, exercises the problem.  I'll see if I can write a failing test.

**Pull request merged**
