### PR TITLE
Add tasks to index EAD from URL

### PR DESCRIPTION
**Pull request by mark-cooper**
https://github.com/sul-dlss/arclight/issues/418

### CODE REVIEW

**Comment by jkeck** [comment]
@mark-cooper looks like there are a few violations of our ruby style guide.

I would be more than happy to work on correcting these with you if you're unfamiliar w/ rubocop.

**Comment by mark-cooper** [comment]
@jkeck I pushed an update. There's still 1 error that I'm not sure what to do with:

```
Offenses:

lib/tasks/index.rake:18:1: C: Metrics/BlockLength: Block has too many lines. [52/25]
namespace :arclight do ...
^^^^^^^^^^^^^^^^^^^^^^

86 files inspected, 1 offense detected
```

Do you have some guidance for how this should be organized? Thanks!

**Comment by jkeck** [comment]
@mark-cooper can you toss it into the `.rubocop.yml`?  We already have some [exemptions](https://github.com/sul-dlss/arclight/blob/master/.rubocop.yml#L29-L34).  It seems like we intended to exclude all rake tasks w/ `tasks/**/*`.  Perhaps we should change that to be just `*.rake` if that works, otherwise adding the `lib/tasks/**/*` would be 👍 too.

**Comment by anarchivist** [comment]
Thanks @mark-cooper! 👏

**Pull request merged**
